[phases.setup]
nixPkgs = ["python311", "ffmpeg", "libffi", "libsodium"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    "/opt/venv/bin/pip install --upgrade pip",
    "/opt/venv/bin/pip install discord.py PyNaCl"
]

[start]
cmd = "/opt/venv/bin/python bot.py"
